# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 360)
        MainWindow.setMinimumSize(QtCore.QSize(950, 360))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.creation_box = QtWidgets.QGroupBox(self.frame)
        self.creation_box.setObjectName("creation_box")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.creation_box)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.creation_box)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.gas_tab = QtWidgets.QWidget()
        self.gas_tab.setObjectName("gas_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gas_tab)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gas_group_box = QtWidgets.QGroupBox(self.gas_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gas_group_box.sizePolicy().hasHeightForWidth())
        self.gas_group_box.setSizePolicy(sizePolicy)
        self.gas_group_box.setMinimumSize(QtCore.QSize(100, 0))
        self.gas_group_box.setAcceptDrops(True)
        self.gas_group_box.setObjectName("gas_group_box")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.gas_group_box)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gas_list_widget = QtWidgets.QListWidget(self.gas_group_box)
        self.gas_list_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gas_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.gas_list_widget.setObjectName("gas_list_widget")
        self.verticalLayout_17.addWidget(self.gas_list_widget)
        self.horizontalLayout_4.addWidget(self.gas_group_box)
        self.gas_line = QtWidgets.QFrame(self.gas_tab)
        self.gas_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.gas_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gas_line.setObjectName("gas_line")
        self.horizontalLayout_4.addWidget(self.gas_line)
        self.gas_frame = QtWidgets.QFrame(self.gas_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gas_frame.sizePolicy().hasHeightForWidth())
        self.gas_frame.setSizePolicy(sizePolicy)
        self.gas_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gas_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gas_frame.setObjectName("gas_frame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.gas_frame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.gas_options_frame = QtWidgets.QFrame(self.gas_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.gas_options_frame.sizePolicy().hasHeightForWidth())
        self.gas_options_frame.setSizePolicy(sizePolicy)
        self.gas_options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gas_options_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gas_options_frame.setObjectName("gas_options_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gas_options_frame)
        self.gridLayout_2.setContentsMargins(0, 3, 0, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gas_vel_label = QtWidgets.QLabel(self.gas_options_frame)
        self.gas_vel_label.setObjectName("gas_vel_label")
        self.gridLayout_2.addWidget(self.gas_vel_label, 0, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.gas_options_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gas_vel_box = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.gas_vel_box.setMaximum(9999.99)
        self.gas_vel_box.setProperty("value", 1.0)
        self.gas_vel_box.setObjectName("gas_vel_box")
        self.horizontalLayout_11.addWidget(self.gas_vel_box)
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.gas_vele_box = QtWidgets.QSpinBox(self.frame_9)
        self.gas_vele_box.setMinimum(-99)
        self.gas_vele_box.setObjectName("gas_vele_box")
        self.horizontalLayout_11.addWidget(self.gas_vele_box)
        self.gridLayout_2.addWidget(self.frame_9, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gas_options_frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.gas_options_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gas_mass_box = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.gas_mass_box.setProperty("value", 0.0)
        self.gas_mass_box.setObjectName("gas_mass_box")
        self.horizontalLayout_13.addWidget(self.gas_mass_box)
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_13.addWidget(self.label_7)
        self.gas_masse_box = QtWidgets.QSpinBox(self.frame_11)
        self.gas_masse_box.setMinimum(-99)
        self.gas_masse_box.setProperty("value", 0)
        self.gas_masse_box.setObjectName("gas_masse_box")
        self.horizontalLayout_13.addWidget(self.gas_masse_box)
        self.gridLayout_2.addWidget(self.frame_11, 1, 1, 1, 1)
        self.gas_rad_label = QtWidgets.QLabel(self.gas_options_frame)
        self.gas_rad_label.setObjectName("gas_rad_label")
        self.gridLayout_2.addWidget(self.gas_rad_label, 2, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.gas_options_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gas_rad_box = QtWidgets.QDoubleSpinBox(self.frame_10)
        self.gas_rad_box.setProperty("value", 1.0)
        self.gas_rad_box.setObjectName("gas_rad_box")
        self.horizontalLayout_12.addWidget(self.gas_rad_box)
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.gas_rade_box = QtWidgets.QSpinBox(self.frame_10)
        self.gas_rade_box.setMinimum(-99)
        self.gas_rade_box.setProperty("value", -1)
        self.gas_rade_box.setObjectName("gas_rade_box")
        self.horizontalLayout_12.addWidget(self.gas_rade_box)
        self.gridLayout_2.addWidget(self.frame_10, 2, 1, 1, 1)
        self.gas_count_label = QtWidgets.QLabel(self.gas_options_frame)
        self.gas_count_label.setObjectName("gas_count_label")
        self.gridLayout_2.addWidget(self.gas_count_label, 3, 0, 1, 1)
        self.gas_count_box = QtWidgets.QSpinBox(self.gas_options_frame)
        self.gas_count_box.setMinimum(1)
        self.gas_count_box.setObjectName("gas_count_box")
        self.gridLayout_2.addWidget(self.gas_count_box, 3, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.verticalLayout_21.addWidget(self.gas_options_frame)
        self.line_2 = QtWidgets.QFrame(self.gas_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_21.addWidget(self.line_2)
        self.gas_create_frame = QtWidgets.QFrame(self.gas_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.gas_create_frame.sizePolicy().hasHeightForWidth())
        self.gas_create_frame.setSizePolicy(sizePolicy)
        self.gas_create_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gas_create_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gas_create_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gas_create_frame.setObjectName("gas_create_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.gas_create_frame)
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.gas_preset_label = QtWidgets.QLabel(self.gas_create_frame)
        self.gas_preset_label.setObjectName("gas_preset_label")
        self.gridLayout.addWidget(self.gas_preset_label, 0, 0, 1, 1)
        self.gas_preset_edit = QtWidgets.QLineEdit(self.gas_create_frame)
        self.gas_preset_edit.setObjectName("gas_preset_edit")
        self.gridLayout.addWidget(self.gas_preset_edit, 0, 1, 1, 1)
        self.gas_create_button = QtWidgets.QPushButton(self.gas_create_frame)
        self.gas_create_button.setObjectName("gas_create_button")
        self.gridLayout.addWidget(self.gas_create_button, 1, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.verticalLayout_21.addWidget(self.gas_create_frame)
        self.horizontalLayout_4.addWidget(self.gas_frame)
        self.tabWidget.addTab(self.gas_tab, "")
        self.sim_tab = QtWidgets.QWidget()
        self.sim_tab.setObjectName("sim_tab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.sim_tab)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sim_group_box = QtWidgets.QGroupBox(self.sim_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_group_box.sizePolicy().hasHeightForWidth())
        self.sim_group_box.setSizePolicy(sizePolicy)
        self.sim_group_box.setMinimumSize(QtCore.QSize(100, 0))
        self.sim_group_box.setAcceptDrops(True)
        self.sim_group_box.setObjectName("sim_group_box")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.sim_group_box)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.sim_list_widget = QtWidgets.QListWidget(self.sim_group_box)
        self.sim_list_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sim_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.sim_list_widget.setObjectName("sim_list_widget")
        self.verticalLayout_20.addWidget(self.sim_list_widget)
        self.horizontalLayout_9.addWidget(self.sim_group_box)
        self.sim_line = QtWidgets.QFrame(self.sim_tab)
        self.sim_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.sim_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sim_line.setObjectName("sim_line")
        self.horizontalLayout_9.addWidget(self.sim_line)
        self.sim_gas_group_box = QtWidgets.QGroupBox(self.sim_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_gas_group_box.sizePolicy().hasHeightForWidth())
        self.sim_gas_group_box.setSizePolicy(sizePolicy)
        self.sim_gas_group_box.setMinimumSize(QtCore.QSize(100, 0))
        self.sim_gas_group_box.setAcceptDrops(True)
        self.sim_gas_group_box.setObjectName("sim_gas_group_box")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.sim_gas_group_box)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.sim_gas_list_widget = QtWidgets.QListWidget(self.sim_gas_group_box)
        self.sim_gas_list_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sim_gas_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.sim_gas_list_widget.setObjectName("sim_gas_list_widget")
        self.verticalLayout_23.addWidget(self.sim_gas_list_widget)
        self.horizontalLayout_9.addWidget(self.sim_gas_group_box)
        self.sim_frame = QtWidgets.QFrame(self.sim_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim_frame.sizePolicy().hasHeightForWidth())
        self.sim_frame.setSizePolicy(sizePolicy)
        self.sim_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sim_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sim_frame.setObjectName("sim_frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.sim_frame)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.sim_options_frame = QtWidgets.QFrame(self.sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.sim_options_frame.sizePolicy().hasHeightForWidth())
        self.sim_options_frame.setSizePolicy(sizePolicy)
        self.sim_options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sim_options_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sim_options_frame.setObjectName("sim_options_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sim_options_frame)
        self.gridLayout_3.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sim_dim_label = QtWidgets.QLabel(self.sim_options_frame)
        self.sim_dim_label.setObjectName("sim_dim_label")
        self.gridLayout_3.addWidget(self.sim_dim_label, 1, 0, 1, 1)
        self.sim_rad_label = QtWidgets.QLabel(self.sim_options_frame)
        self.sim_rad_label.setObjectName("sim_rad_label")
        self.gridLayout_3.addWidget(self.sim_rad_label, 0, 0, 1, 1)
        self.sim_method_label = QtWidgets.QLabel(self.sim_options_frame)
        self.sim_method_label.setObjectName("sim_method_label")
        self.gridLayout_3.addWidget(self.sim_method_label, 2, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.sim_options_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sim_rad_box = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.sim_rad_box.setMinimum(0.01)
        self.sim_rad_box.setProperty("value", 1.0)
        self.sim_rad_box.setObjectName("sim_rad_box")
        self.horizontalLayout_7.addWidget(self.sim_rad_box)
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.sim_rade_box = QtWidgets.QSpinBox(self.frame_8)
        self.sim_rade_box.setMinimum(-99)
        self.sim_rade_box.setObjectName("sim_rade_box")
        self.horizontalLayout_7.addWidget(self.sim_rade_box)
        self.gridLayout_3.addWidget(self.frame_8, 0, 1, 1, 2)
        self.sim_dim_box = QtWidgets.QSpinBox(self.sim_options_frame)
        self.sim_dim_box.setMinimum(2)
        self.sim_dim_box.setMaximum(3)
        self.sim_dim_box.setObjectName("sim_dim_box")
        self.gridLayout_3.addWidget(self.sim_dim_box, 1, 1, 1, 2)
        self.sim_method_box = QtWidgets.QComboBox(self.sim_options_frame)
        self.sim_method_box.setObjectName("sim_method_box")
        self.sim_method_box.addItem("")
        self.sim_method_box.addItem("")
        self.sim_method_box.addItem("")
        self.gridLayout_3.addWidget(self.sim_method_box, 2, 1, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.verticalLayout_22.addWidget(self.sim_options_frame)
        self.line_3 = QtWidgets.QFrame(self.sim_frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_22.addWidget(self.line_3)
        self.sim_create_frame = QtWidgets.QFrame(self.sim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.sim_create_frame.sizePolicy().hasHeightForWidth())
        self.sim_create_frame.setSizePolicy(sizePolicy)
        self.sim_create_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.sim_create_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sim_create_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sim_create_frame.setObjectName("sim_create_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.sim_create_frame)
        self.gridLayout_4.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sim_preset_label = QtWidgets.QLabel(self.sim_create_frame)
        self.sim_preset_label.setObjectName("sim_preset_label")
        self.gridLayout_4.addWidget(self.sim_preset_label, 0, 0, 1, 1)
        self.sim_preset_edit = QtWidgets.QLineEdit(self.sim_create_frame)
        self.sim_preset_edit.setObjectName("sim_preset_edit")
        self.gridLayout_4.addWidget(self.sim_preset_edit, 0, 1, 1, 1)
        self.sim_create_button = QtWidgets.QPushButton(self.sim_create_frame)
        self.sim_create_button.setObjectName("sim_create_button")
        self.gridLayout_4.addWidget(self.sim_create_button, 1, 0, 1, 2)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 2)
        self.verticalLayout_22.addWidget(self.sim_create_frame)
        self.horizontalLayout_9.addWidget(self.sim_frame)
        self.tabWidget.addTab(self.sim_tab, "")
        self.anim_tab = QtWidgets.QWidget()
        self.anim_tab.setObjectName("anim_tab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.anim_tab)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.anim_group_box = QtWidgets.QGroupBox(self.anim_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anim_group_box.sizePolicy().hasHeightForWidth())
        self.anim_group_box.setSizePolicy(sizePolicy)
        self.anim_group_box.setMinimumSize(QtCore.QSize(100, 0))
        self.anim_group_box.setAcceptDrops(True)
        self.anim_group_box.setObjectName("anim_group_box")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.anim_group_box)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.anim_list_widget = QtWidgets.QListWidget(self.anim_group_box)
        self.anim_list_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.anim_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.anim_list_widget.setObjectName("anim_list_widget")
        self.verticalLayout_18.addWidget(self.anim_list_widget)
        self.horizontalLayout_10.addWidget(self.anim_group_box)
        self.anim_line = QtWidgets.QFrame(self.anim_tab)
        self.anim_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.anim_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.anim_line.setObjectName("anim_line")
        self.horizontalLayout_10.addWidget(self.anim_line)
        self.anim_frame = QtWidgets.QFrame(self.anim_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anim_frame.sizePolicy().hasHeightForWidth())
        self.anim_frame.setSizePolicy(sizePolicy)
        self.anim_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.anim_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.anim_frame.setObjectName("anim_frame")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.anim_frame)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.anim_options_frame = QtWidgets.QFrame(self.anim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.anim_options_frame.sizePolicy().hasHeightForWidth())
        self.anim_options_frame.setSizePolicy(sizePolicy)
        self.anim_options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.anim_options_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.anim_options_frame.setObjectName("anim_options_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.anim_options_frame)
        self.gridLayout_6.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.anim_fps_label = QtWidgets.QLabel(self.anim_options_frame)
        self.anim_fps_label.setObjectName("anim_fps_label")
        self.gridLayout_6.addWidget(self.anim_fps_label, 0, 0, 1, 1)
        self.anim_speed_label = QtWidgets.QLabel(self.anim_options_frame)
        self.anim_speed_label.setObjectName("anim_speed_label")
        self.gridLayout_6.addWidget(self.anim_speed_label, 1, 0, 1, 1)
        self.anim_speed_box = QtWidgets.QDoubleSpinBox(self.anim_options_frame)
        self.anim_speed_box.setMinimum(0.01)
        self.anim_speed_box.setProperty("value", 1.0)
        self.anim_speed_box.setObjectName("anim_speed_box")
        self.gridLayout_6.addWidget(self.anim_speed_box, 1, 1, 1, 1)
        self.anim_fps_box = QtWidgets.QSpinBox(self.anim_options_frame)
        self.anim_fps_box.setMinimum(1)
        self.anim_fps_box.setMaximum(9999)
        self.anim_fps_box.setProperty("value", 60)
        self.anim_fps_box.setObjectName("anim_fps_box")
        self.gridLayout_6.addWidget(self.anim_fps_box, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.verticalLayout_24.addWidget(self.anim_options_frame)
        self.line_4 = QtWidgets.QFrame(self.anim_frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_24.addWidget(self.line_4)
        self.anim_create_frame = QtWidgets.QFrame(self.anim_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.anim_create_frame.sizePolicy().hasHeightForWidth())
        self.anim_create_frame.setSizePolicy(sizePolicy)
        self.anim_create_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.anim_create_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.anim_create_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.anim_create_frame.setObjectName("anim_create_frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.anim_create_frame)
        self.gridLayout_7.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.anim_preset_label = QtWidgets.QLabel(self.anim_create_frame)
        self.anim_preset_label.setObjectName("anim_preset_label")
        self.gridLayout_7.addWidget(self.anim_preset_label, 0, 0, 1, 1)
        self.anim_preset_edit = QtWidgets.QLineEdit(self.anim_create_frame)
        self.anim_preset_edit.setObjectName("anim_preset_edit")
        self.gridLayout_7.addWidget(self.anim_preset_edit, 0, 1, 1, 1)
        self.anim_create_button = QtWidgets.QPushButton(self.anim_create_frame)
        self.anim_create_button.setObjectName("anim_create_button")
        self.gridLayout_7.addWidget(self.anim_create_button, 1, 0, 1, 2)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 2)
        self.verticalLayout_24.addWidget(self.anim_create_frame)
        self.horizontalLayout_10.addWidget(self.anim_frame)
        self.tabWidget.addTab(self.anim_tab, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout_8.addWidget(self.creation_box)
        self.execution_box = QtWidgets.QGroupBox(self.frame)
        self.execution_box.setObjectName("execution_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.execution_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.execution_box)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.simulation_combobox = QtWidgets.QComboBox(self.execution_box)
        self.simulation_combobox.setObjectName("simulation_combobox")
        self.gridLayout_5.addWidget(self.simulation_combobox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.execution_box)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.animation_combobox = QtWidgets.QComboBox(self.execution_box)
        self.animation_combobox.setObjectName("animation_combobox")
        self.gridLayout_5.addWidget(self.animation_combobox, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.execution_box)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setWhatsThis("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_6.addWidget(self.plainTextEdit)
        self.gridLayout_5.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.execution_box)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 3, 0, 1, 2)
        self.run_sim_button = QtWidgets.QPushButton(self.execution_box)
        self.run_sim_button.setObjectName("run_sim_button")
        self.gridLayout_5.addWidget(self.run_sim_button, 4, 0, 1, 2)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 3)
        self.horizontalLayout_8.addWidget(self.execution_box)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 21))
        self.menubar.setObjectName("menubar")
        self.menuReload_Preset = QtWidgets.QMenu(self.menubar)
        self.menuReload_Preset.setObjectName("menuReload_Preset")
        self.menuAdditional_Investigations = QtWidgets.QMenu(self.menubar)
        self.menuAdditional_Investigations.setObjectName("menuAdditional_Investigations")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReload = QtWidgets.QAction(MainWindow)
        self.actionReload.setObjectName("actionReload")
        self.actionShow_Gas_Laws = QtWidgets.QAction(MainWindow)
        self.actionShow_Gas_Laws.setObjectName("actionShow_Gas_Laws")
        self.actionPlot_B_against_V = QtWidgets.QAction(MainWindow)
        self.actionPlot_B_against_V.setObjectName("actionPlot_B_against_V")
        self.actionFind_B_Graphically = QtWidgets.QAction(MainWindow)
        self.actionFind_B_Graphically.setObjectName("actionFind_B_Graphically")
        self.menuReload_Preset.addAction(self.actionReload)
        self.menuAdditional_Investigations.addAction(self.actionShow_Gas_Laws)
        self.menuAdditional_Investigations.addAction(self.actionPlot_B_against_V)
        self.menuAdditional_Investigations.addAction(self.actionFind_B_Graphically)
        self.menubar.addAction(self.menuReload_Preset.menuAction())
        self.menubar.addAction(self.menuAdditional_Investigations.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyBAllS"))
        self.creation_box.setTitle(_translate("MainWindow", "Creation"))
        self.gas_group_box.setToolTip(_translate("MainWindow", "Select an existing preset to load its values. Press del to delete selected presets."))
        self.gas_group_box.setTitle(_translate("MainWindow", "Existing Presets"))
        self.gas_vel_label.setText(_translate("MainWindow", "Modal Velocity:"))
        self.label_4.setText(_translate("MainWindow", "E"))
        self.label_6.setText(_translate("MainWindow", "Mass"))
        self.label_7.setText(_translate("MainWindow", "E"))
        self.gas_rad_label.setText(_translate("MainWindow", "Radius:"))
        self.label_5.setText(_translate("MainWindow", "E"))
        self.gas_count_label.setText(_translate("MainWindow", "Count:"))
        self.gas_preset_label.setText(_translate("MainWindow", "Preset Name:"))
        self.gas_create_button.setText(_translate("MainWindow", "Save Preset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gas_tab), _translate("MainWindow", "Gas"))
        self.sim_group_box.setToolTip(_translate("MainWindow", "Select an existing preset to load its values. Press del to delete selected presets."))
        self.sim_group_box.setTitle(_translate("MainWindow", "Existing Presets"))
        self.sim_gas_group_box.setTitle(_translate("MainWindow", "Gases"))
        self.sim_dim_label.setText(_translate("MainWindow", "Dimensions:"))
        self.sim_rad_label.setText(_translate("MainWindow", "Container Radius:"))
        self.sim_method_label.setText(_translate("MainWindow", "Simulation Method:"))
        self.label_3.setText(_translate("MainWindow", "E"))
        self.sim_method_box.setCurrentText(_translate("MainWindow", "1"))
        self.sim_method_box.setItemText(0, _translate("MainWindow", "1"))
        self.sim_method_box.setItemText(1, _translate("MainWindow", "2"))
        self.sim_method_box.setItemText(2, _translate("MainWindow", "3"))
        self.sim_preset_label.setText(_translate("MainWindow", "Preset Name:"))
        self.sim_create_button.setText(_translate("MainWindow", "Save Preset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sim_tab), _translate("MainWindow", "Simulation"))
        self.anim_group_box.setToolTip(_translate("MainWindow", "Select an existing preset to load its values. Press del to delete selected presets."))
        self.anim_group_box.setTitle(_translate("MainWindow", "Existing Presets"))
        self.anim_fps_label.setText(_translate("MainWindow", "Frames per Second:"))
        self.anim_speed_label.setText(_translate("MainWindow", "Speed up:"))
        self.anim_preset_label.setText(_translate("MainWindow", "Preset Name:"))
        self.anim_create_button.setText(_translate("MainWindow", "Save Preset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.anim_tab), _translate("MainWindow", "Animation"))
        self.execution_box.setTitle(_translate("MainWindow", "Execution"))
        self.label.setText(_translate("MainWindow", "Simulation"))
        self.label_2.setText(_translate("MainWindow", "Animation"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Overrides"))
        self.plainTextEdit.setToolTip(_translate("MainWindow", "Enter variables to override here as key:value pairs, as in a printed dictionary. Eg. {\'dimensions\': 2}"))
        self.run_sim_button.setText(_translate("MainWindow", "Run Simulation"))
        self.menuReload_Preset.setTitle(_translate("MainWindow", "Presets"))
        self.menuAdditional_Investigations.setTitle(_translate("MainWindow", "Additional Investigations"))
        self.actionReload.setText(_translate("MainWindow", "Reload"))
        self.actionShow_Gas_Laws.setText(_translate("MainWindow", "Show Gas Laws"))
        self.actionPlot_B_against_V.setText(_translate("MainWindow", "Plot b against V_G"))
        self.actionFind_B_Graphically.setText(_translate("MainWindow", "Find b Graphically"))

